import 'package:australti_ecommerce_app/models/store.dart';
import 'package:australti_ecommerce_app/models/user.dart';

const storesList = <Store>[
  Store(
      id: '1-a',
      about: '',
      name: 'Mc Donnals',
      user: User(uid: '1'),
      image: '',
      service: 1,
      products: 4,
      timeDelivery: '15 - 30',
      percentOff: 30,
      trophys: 2,
      isEco: false),
  Store(
      id: '1',
      about: '',
      name: 'Hola 2',
      user: User(uid: '1'),
      image: '',
      service: 2,
      products: 4,
      timeDelivery: '15 - 30',
      percentOff: 30,
      trophys: 2,
      isEco: false),
  Store(
      id: '2',
      about: '',
      name: 'Hola 3',
      user: User(uid: '1'),
      image: '',
      service: 3,
      products: 4,
      timeDelivery: '15 - 30',
      percentOff: 30,
      trophys: 3,
      isEco: false),
  Store(
      id: '2-a',
      about: '',
      name: 'Hola 3',
      user: User(uid: '1'),
      image: '',
      service: 3,
      products: 4,
      timeDelivery: '15 - 30',
      percentOff: 30,
      trophys: 3,
      isEco: false),
  Store(
      id: '2-b',
      about: '',
      name: 'Hola 3',
      user: User(uid: '2'),
      image: '',
      service: 3,
      products: 4,
      timeDelivery: '15 - 30',
      percentOff: 30,
      trophys: 3,
      isEco: false),
  Store(
      id: '2-c',
      about: '',
      name: 'Hola 3',
      user: User(uid: '2'),
      image: '',
      service: 3,
      products: 4,
      timeDelivery: '15 - 30',
      percentOff: 30,
      trophys: 3,
      isEco: false),
  Store(
      id: '3',
      about: '',
      name: 'Hola 1',
      user: User(uid: '2'),
      image: '',
      service: 1,
      products: 4,
      timeDelivery: '15 - 30',
      percentOff: 30,
      trophys: 2,
      isEco: false),
  Store(
      id: '4',
      about: '',
      name: 'Hola 1',
      user: User(uid: '2'),
      image: '',
      service: 1,
      products: 4,
      timeDelivery: '15 - 30',
      percentOff: 30,
      trophys: 2,
      isEco: false),
  Store(
      id: '5',
      about: '',
      name: 'Hola 1',
      user: User(uid: '2'),
      image: '',
      service: 1,
      products: 4,
      timeDelivery: '15 - 30',
      percentOff: 30,
      trophys: 2,
      isEco: false),
];
